### ISSUE TITLE
A compile error occurs in SceneHandle

### ISSUE THREAD

**Issue by mokapants** [mewlist/MewCore#37]
The following compile error occurs when adding MewCore from PackageManager.
This error occurs even when a new project file is created and only MewCore is installed.

> ```Library\PackageCache\st.mewli.core@18ddd596a5\Runtime\Assets\Scene\SceneHandle.cs(49,17): error CS1061: 'AsyncOperation' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'AsyncOperation' could be found (are you missing a using directive or an assembly reference?)```

**Comment by mewlist** [comment]
This bug is found at https://github.com/mewlist/MewCore/pull/35/files#diff-2f66eed87ac1058bf291c9c00aaa7586f064b3609c6e80653fdeb73dbcdc8fafR49.

This issue reproduced on only Unity2022.
On Unity 6 this code is compiled.

I have fixed it, using version compatibility scene load API.
#38 

Thank you.
